imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

## Third Party Bundles
########################

# JMS Serializer
# ref: http://jmsyst.com/bundles/JMSSerializerBundle
jms_serializer:
    visitors:
        json:
            options: 256
# ref: https://github.com/schmittjoh/JMSSerializerBundle/pull/270#issuecomment-41034000
framework:
    jms_serializer.cache_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

# FOS Rest
# ref: https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/doc/index.md
fos_rest:
    routing_loader:
        include_format: false
    view:
        formats:
            xml: true
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    format_listener: 
        rules:
            - { path: '^/api/doc', priorities: [ 'text/html' ] }
            - { path: '^/api', priorities: ['json', 'xml'] }
            - { path: '^/image', priorities: ['jpeg', 'gif'], fallback_format: false, prefer_extension: true }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }

# Nelmio API Doc
# ref: https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/index.md
nelmio_api_doc:
    sandbox:
        request_format:
            method: accept_header
            default_format: json

# Bazinga Geocoder
# ref: https://github.com/geocoder-php/BazingaGeocoderBundle/blob/master/Resources/doc/index.md
bazinga_geocoder:
    providers:
        google_maps:
                locale: null
                region: null
                use_ssl: true
                api_key: AIzaSyCs6WcHpnG2k1N5RTo12B_D2dgp48EJykU
framework:
    trusted_proxies: ['127.0.0.1']

# LeaseWeb Memcache
# ref: https://github.com/LeaseWeb/LswMemcacheBundle
lsw_memcache:
    session:
        client: default
        prefix: "session_"
        ttl: 7200
        locking: true
        spin_lock_wait: 150000
    clients:
        default:
            hosts:
              - { dsn: 127.0.0.1, port: 11211 }